### ISSUE TITLE
Entrypoint - Špatná detekce wwwDir

### ISSUE THREAD

**Issue by novjan** [contributte/console#15]
Ahoj @f3l1x.
Chci říct, že super práce. Právě přepisujem kod a nahrazujem Kdyby\Doctrine pomocí Nettrine :)
Nicméně k problému.
Mohl bys prosím poradit, případně to i doplnit do DOC, jak správně detekovat wwwDir?

Jde o to, že kdy použiji tvůj příklad i s umístěním, tak se špatně nastaví wwwDir.
https://github.com/contributte/console/tree/master/.docs#entrypoint

Což není vůbec ideální a některé věci začnou fungovat neočekáváně.

Nejsnadnější řešení by bylo přesunout script vedle index.php, ale to se mi opravdu nechce.
V podstatě bych potřeboval po vytvoření containeru změnit wwwDir parameter.

**Comment by mabar** [comment]
Do parametru wwwDir ti to vkládá cestu ke složce /bin, že?
Nette nastavuje wwwDir podle [vstupního bodu do aplikace](https://github.com/nette/bootstrap/blob/master/src/Bootstrap/Configurator.php#L161), což je pro většinu lidí www/index.php. Ideální by bylo nejspíš nastavovat natvrdo cestu do /www

Nejsnadnější pro tebe bude nastavit v bootstrap.php `$configurator->addParameters(['wwwDir' => dirname(__DIR__) . '/www']);`

**Comment by novjan** [comment]
@mabar Přesně tak díky, tohle funguje 👍 
ŘÍkáš nejsnadnější. Znamená to, že existuje složitější, ale čistější způsob?

**Comment by mabar** [comment]
Já mám třeba parametr rootDir a z něho se odvíjí všechny ostatní cesty. Vyjde to prakticky nastejno.
Jako lepší způsob mi přijde změnit to přímo v Nette, ten výchozí způsob je strašně moc magický.

**Comment by f3l1x** [comment]
Souhlas, v bootstrap.php si uprav appDir, wwwDir, xyzDir a je to. :-)
