### ISSUE TITLE
Console Helpers support

### ISSUE THREAD

**Issue by enumag** [contributte/console#2]
I like how minimal this integration of Kdyby console is. However I still think it should support [console helpers](http://symfony.com/doc/current/components/console/helpers/index.html). See the relevant lines in [Kdyby](https://github.com/Kdyby/Console/blob/9dbfd0603a9c3c380a9a3c6a34c3cf4112c133cd/src/Kdyby/Console/DI/ConsoleExtension.php#L98-L138).

**Comment by f3l1x** [comment]
@enumag Thanks. We might support it. Good point. I'll implement it.

Any other thoughts/ideas? Please consider it as small as possible. ;-)

**Comment by TomasVotruba** [comment]
@enumag HelperSet is just services locator. I'm strictly against it.

What is the advantage over constructor injection?

**Comment by enumag** [comment]
@TomasVotruba Symfony commands are not really compatible with constructor injection because all of them are instantiated every time you use console - instead of only the one you need. If you know a solution, please share.

**Comment by TomasVotruba** [comment]
@enumag Why is that issue?

**Comment by enumag** [comment]
@TomasVotruba It is a problem because I don't want to create all the services any command might have a dependency on every time I run any of them. Sometimes I use commands as long-running processes and I want to reduce their memory usage - meaning it's better to instantiate only what is necessary for the given command. This is the same thing as with Presenters/Controllers - would you want to instantiate all of them for every http request? Me neither. But this of course means there is some sort of service locator in PresenterFactory/ControllerResolver - and that's ok with me.

The thing with service locator is that it is not necessarily bad nor fully replaceable by dependency injection. It just should be used carefully and mainly hidden in libraries, but not used in applications themselves. This is of course why you dislike console helper. And I agree with you, I don't like them either. The service locator would be far better to have in `Symfony\Component\Console\Application` to load commands, not in the commands themselves. The real issue here is that `Symfony\Component\Console\Command\Command` is not static and implement this would require hacks involving `ReflectionClass::newInstanceWithoutConstructor()`.

**Comment by TomasVotruba** [comment]
@enumag Still, Symfony\Console issue. This is wrong level of abstraction to workaround this.

**Comment by enumag** [comment]
@TomasVotruba Precisly. But as there is no better solution at the moment it is still needed.

**Comment by f3l1x** [comment]
@enumag I've discovered that some default helpers are already setup in `Symfony\Application` (https://github.com/symfony/console/blob/v3.2.8/Application.php#L84).

I've merged #4 just few minutes ago. Do you need anything more? I saw some Container and Presenter helpers in Kdyby. Do you need them too?

**Comment by enumag** [comment]
I think #4 is enough. Please don't pollute this package with Kdyby garbage.

**Comment by f3l1x** [comment]
@enumag Great. But, what about ContainerHelper or PresenterHelper, do you use them? In case of you do, do you want to create them for each project?

**Comment by enumag** [comment]
ContainerHelper is about the only way to use services in commands. Or do you know any other? PresenterHelper - no thanks.

**Comment by f3l1x** [comment]
@enumag Could we consider this issue as done? 

https://github.com/contributte/console/commit/9fe2639c3e06a8684b973153668d9ecc5adc6756

------

I experiment with some ProxyCommands for lazy-loading. We'll see. :-)

**Comment by enumag** [comment]
Yeah, thanks!.
