### ISSUE TITLE
Provide CLI mode, e.q. Contributte\Console\DI\ConsoleExtension(%consoleMode%).

### ISSUE THREAD

**Issue by peldax** [contributte/console#21]
Ahoj,

toto je spíše dotaz, nerozumím této hlášce kterou dostanu po spuštění konzole když postupuji přesně podle tutorialu. Hláška samozřejmě zmizí pokud přidám parametr v konfiguraci:

```
extensions:
    console: Contributte\Console\DI\ConsoleExtension(true)
```

ale ta kontrola tam předpokládám k něčemu je, tak se chci zeptat kde dělám chybu, případně poprosit o dopsání dokumentace.

Jinak super práce, taky jsem nesnášel ohýbání routeru.

Díky.

**Comment by mabar** [comment]
symfony/console je spustitelná i mimo konzoli. Tohle nastavení určuje, zda chceš, aby se symfony/console registrovala do DIC. Napovídá to %consoleMode%, jelikož je to nastavení co chce většina uživatelů - tedy používat symfony/console jen přes konzoli.

A příště prosím anglicky.
