### ISSUE TITLE
Lazy mode, BC break?

### ISSUE THREAD

**Issue by Rixafy** [contributte/console#28]
In previous version (master) was default lazy value false, in current configuration schema in "next" branch is that value set to true, so everyone with zero extension configuration runs in problem that he needs to define his command names statically.

Solution would be remove this option, and register lazy commands automatically when they have `tags: [console.command: app:foo]` in .neon configuration or they have configured default name statically. Instead of throwing ServiceCreationException, https://github.com/contributte/console/blob/next/src/DI/ConsoleExtension.php#L181 can be `$applicationDef->addSetup('add', [$service]);` and lazy configuration will not be needed.

**Comment by f3l1x** [comment]
Laziness by default is intended. You could disable it, if you want.
