### ISSUE TITLE
Basic commands [idea]

### ISSUE THREAD

**Issue by f3l1x** [contributte/console#3]
I'm just thinking about some basic commands.

### Assets
- `nette:assets:combine` (https://github.com/nette/sandbox/commit/52787b6b65405228e1104406699fcb8e0fd2f080)

### Cache

- `nette:cache:purge`

### Database
- `nette:database:dump`

### DI

- `nette:di:purge`
- `nette:di:warmup`

### NEON

Solved via Neonizer - https://github.com/contributte/neonizer.

### Latte

- `nette:latte:purge`
- `nette:latte:warmup`

### Router
- `nette:router:dump`
- `nette:router:match [url]`
- `nette:router:link [args]`

### Security
- `nette:security:password [password]`
- `nette:security:acl --all --roles --resources`

### Utils

- `nette:utils:random`
- `nette:utils:json:lint`

### Validator (really?)
- `nette:validator:email`
- `nette:validator:url`

**Comment by f3l1x** [comment]
What do you think @enumag @tomasvotruba?

**Comment by TomasVotruba** [comment]
Good idea :+1: . I'd personally appreciate command alternative for what I already do manually:

- `nette:cache:purge`
- `nette:security:password`
- `nette:database:dump`

**Comment by enumag** [comment]
Looks good. It would be nice to have a command(s) to precompile dic, latte templates, etc. when deploying to production (and not wait for the first request). But I'm not sure how to compile the normal DIC in CLI mode.

**Comment by mabar** [comment]
`nette:cache:purge` - I would preffer an cache cleaner extension and command as bridge only. Cache in temp/ directory is not the only one so interface for cleaning from redis, memcache, database etc. would be nice.
```php
interface Cleaner {
	public function clean();
}
```

`nette:cache:warmup` - Not sure about DI, but templates should not be difficult (if you are not using all templates, like I don't do, it becomes very inefficient).
Find all template files (eg. trhrough finder) and call `$templateFactory->createTemplate()->getLatte()->warmupCache($fileName);`

**Comment by f3l1x** [comment]
Something is growing:

![selection_001](https://user-images.githubusercontent.com/538058/38587805-2bbca708-3d23-11e8-8fba-f519fffacf2d.png)

**Comment by f3l1x** [comment]
We'are working on that here: https://github.com/contributte/console-extra

**Comment by f3l1x** [comment]
I'm closing it, we're done here. 🎉 

Take a look at https://github.com/contributte/console-extra
