### ISSUE TITLE
The option 'console › version' expects to be string, float given.

### ISSUE THREAD

**Issue by janbarasek** [contributte/console#31]
In documentation https://github.com/contributte/console/blob/master/.docs/README.md#configuration is example value: `version: 1.0`, but Nette 3.0 throw exception:

> Nette\DI\InvalidConfigurationException
>
> The option 'console › version' expects to be string, float 3.0 given.

Correct value option is `version: '1.0'`, or add accept float input.

**Comment by mabar** [comment]
Fixed by https://github.com/contributte/console/commit/892c180f35881c245aa12e8fb3c457b0ba67b206
