### ISSUE TITLE
PHP 7.3 support

### ISSUE THREAD

**Issue by JanGalek** [contributte/console#32]
Hi, I started work on new project with PHP 7.3, and there is problem with resolving requirements symfony/console.

```
Problem 1
    - symfony/console 4.4.x-dev requires php ^7.1.3 -> your PHP version (7.3.6-1+ubuntu18.04.1+deb.sury.org+1) overridden by "config.platform.php" version (7.1) does not satisfy that requirement.
```

**Comment by mabar** [comment]
Your platform.php config says "act like I am using php 7.1.0"
https://getcomposer.org/doc/06-config.md#platform
