### ISSUE TITLE
Not able to build without helperSet

### ISSUE THREAD

**Issue by akadlec** [contributte/console#38]
Trying to migrate from kdyby. My conf:
```
console:
	name: xxx
	version: '1.0'
	catchExceptions: true
	autoExit: true
	url: http://example.com
	lazy: false
	helperSet: null
	helpers: []
```
And build throw error:

`Nette\DI\ServiceCreationException: Service 'console.helperSet': Factory and type are missing in definition of service.`

ver:
```
  - Installing nette/di (v3.0.1): Cloning 4aff517a1c from cache
  - Installing contributte/console (v0.7.1): Cloning a676e1a395 from cache
```

**Comment by akadlec** [comment]
and why this ext is not using some default values?

**Comment by akadlec** [comment]
Had to update config to this:

```
console:
	helperSet: \Symfony\Component\Console\Helper\HelperSet
```

with version 0.6 it is working with `null`

**Comment by f3l1x** [comment]
Hi, I will take a look, thanks.
