### ISSUE TITLE
Packages and PHP requirements update

### ISSUE THREAD

**Issue by pilarik31** [contributte/console#58]
Hello,

I wanted to make a PR to update `symfony/console` and minimal PHP version, but I noticed that the package still has CI actions for EOL PHP versions, like 7.2.

So my question is - is it needed to support old PHP version in CI?
If so, is it possible to update dependencies without breaking the CI?

Downloading old version would still be possible, through versioning on Packagist.

Kind regards
John

**Comment by f3l1x** [comment]
Hi @pilarik31. There will be a mass update for all packages supporting only PHP 8.0+. I guess. 

Until that you can prepare a PR with upgrade. To know that everything works great.

**Comment by f3l1x** [comment]
Solved.

Ref: https://github.com/contributte/contributte/issues/56
