### ISSUE TITLE
Get rid of foo in sake of newbies

### ISSUE THREAD

**Issue by dakur** [contributte/console#64]
I needed to [explain how commands work](https://forum.nette.org/cs/34921-appite-je-mozne-volat-controllery-z-console#p218882), but docs [were not much helpful](https://github.com/contributte/console/tree/master/.docs#create-command ).

Couldn't be there rather some artificial `Article` or `UserModel` injected, some `article:add` or `users:add` command registered and instead of "Some magic" some code demonstrated?

I remember well how much I struggled with these foo stuff many years ago when I was trying to understand what are interfaces for. I actually didn't understand it then until years later someone showed me real world interface.

Reference: https://www.google.com/search?q=why+not+to+use+foo

**Comment by f3l1x** [comment]
Sure, why not. Will you prepare PR?

**Comment by dakur** [comment]
I think I could.

**Comment by dakur** [comment]
@f3l1x I've tried in #65

**Comment by f3l1x** [comment]
Merged, thank you.
