### ISSUE TITLE
ConsoleExtension doesn't support `Nette\DI\Statement`

### ISSUE THREAD

**Issue by silen-z** [contributte/console#67]
When using global functions in NEON config like: `not(%debugMode%)` they get created by DI as `Nette\DI\Statement` but [here](https://github.com/contributte/console/blob/v0.5/src/DI/ConsoleExtension.php#L74) ConsoleExtension is casting them to bool which silently fails and evaulates to `true` regardless of the statement value

Version: 0.5.0

**Comment by f3l1x** [comment]
Good catch. Can you prepare PR? Some test would be excellent.
